version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=martinnyborg/pocuter-compiler -t martinnyborg/pocuter-compiler .
            docker tag martinnyborg/pocuter-compiler "martinnyborg/pocuter-compiler:${CIRCLE_SHA1}"
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar martinnyborg/pocuter-compiler
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/app.tar
      - deploy:
          name: Push application Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "main" ]; then
              docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
              docker push martinnyborg/pocuter-compiler:latest
              docker push martinnyborg/pocuter-compiler:${CIRCLE_SHA1}
            fi